site_name: Deluge
site_url: https://deluge-torrent.org
theme:
  name: material
  logo: assets/deluge_logo.png
  favicon: assets/deluge_icon.png
  features:
    - navigation.sections
    - navigation.path
    - navigation.indexes
  font:
    test: Open Sans
  palette:
    scheme: deluge
  custom_dir: overrides
plugins:
  - search
  - awesome-pages
markdown_extensions:
  - pymdownx.magiclink
extra_css:
  - stylesheets/deluge_stormy_day.css
  - stylesheets/deluge_header_nav.css
  - stylesheets/extra.css
nav:
  - Home: index.md
  - Download: download.md
  - Support:
      - userguide/index.md
      - ... | installing/**/*.md
      - ... | userguide/**/*.md
      - FAQ: faq.md
      - Troubleshooting: troubleshooting.md
      - Contact: contactus.md
  - Plugins:
      - plugins/index.md
      - ... | plugins/*.md
  - Contributing:
      - Bug Report: contributing/bugreporting.md
      - Coding Style: contributing/codingstyle.md
      - Pull Requests: contributing/pullrequests.md
  - Development:
      - Development: development/index.md
      - ... | development/**/*.md
validation:
  omitted_files: warn
  absolute_links: relative_to_docs
  unrecognized_links: warn
  anchors: warn
