site_name: Deluge
site_url: https://deluge-torrent.org
theme:
  name: material
  logo: assets/deluge_logo.png
  favicon: assets/deluge_icon.png
  features:
    - navigation.sections
    - navigation.path
    - navigation.indexes
  font:
    test: Open Sans
    #text: Josefin Sans
  palette:
    scheme: deluge
  custom_dir: overrides
markdown_extensions:
  - pymdownx.magiclink
extra_css:
  - stylesheets/deluge_stormy_day.css
  - stylesheets/deluge_header_nav.css
  - stylesheets/extra.css
nav:
  - Home: index.md
  - Download: download.md
  - Plugins: plugins
  - Support:
      - FAQ: faq.md
      - User Guide: userguide/index.md
  - Contributing:
      - Bug Report: contributing/bugreporting.md
      - Coding Style: contributing/codingstyle.md
      - Pull Requests: contributing/pullrequests.md
  - Development:
      - Development: development/index.md
