name: Docker


on:
  push:
    branches:
      - develop
      - master
    tags:
      - 'v*.*.*'
    paths-ignore:
      - '**/*.md'
      - '.gitignore'
      - '.github/**'
      - '!.github/workflows/docker.yml'
  workflow_dispatch:


jobs:
  build-and-push:
    name: Build and Push
    uses: codex-storage/github-actions/.github/workflows/docker-reusable.yml@master
    with:
      docker_file: docker/deluge.Dockerfile
      dockerhub_repo: codexstorage/deluge
      tag_latest: ${{ github.ref_name == github.event.repository.default_branch || startsWith(github.ref, 'refs/tags/') }}
    secrets: inherit
